development:
  access_key_id: "KEY"
  secret_access_key: "SECRET"
  bucket: "BUCKET"
  revision: "0.0.10.4"

production:
  access_key_id: "KEY"
  secret_access_key: "SECRET"
  bucket: "BUCKET"
  revision: "0.0.10.4"
